# FROM nginx:alpine

# COPY dist /usr/share/nginx/html
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# EXPOSE 80

# CMD ["nginx", "-g", "daemon off;"]



# Etapa única: entorno de desarrollo
FROM node:20-slim

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

# Expone el puerto típico de desarrollo, como 5173 (Vite), 3000 (React), 4200 (Angular)
EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
